### ISSUE TITLE
Audio loops in location after action taken

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/pbj_pup#2]
Hi,

When you eat or punch either of the items, the audio loops repeatedly in the location where you took the action. As you walk away from said location, the audio becomes weaker and disappears (similar to how the Jukebox mod works). If you log off and log on again, this is no longer a problem.

If you need to test this out, feel free to use THE CREATIVE GARDENS in the v5 server list.

Thank you!

**Comment by SmallJoker** [comment]
d1278a8
